---
title: "SA Indirect Quality"
author: "Mārtiņš Liberts"
date: "2019-09-26"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## History

- The development started during the RJDemetra hackathon
    - June 1-2, 2019
    - Deutsche Bundesbank, Frankfurt am Main, Germany
    - by Dr. Andreas Dietrich and Dr. Mārtiņš Liberts


## Aim

- R package
- quality evaluation for the indirect seasonal adjustment
- according to the [Handbook on Seasonal Adjustment](http://ec.europa.eu/eurostat/web/products-manuals-and-guidelines/-/KS-GQ-18-001) (2018)
- Section 18.3.2 "Quality Measures"


## Step 1

Functions for quality criteria calculation for two time series – directly and indirectly adjusted (tsda and tsia). Could be the seasonally adjusted series, the trend-cycle estimates and the seasonal components.

- Input: two sets of time series (two `ts` objects with three time series – `sa`, `t`, `i`).
- Parameters:
    - Length of time series in years (could be decimal): full (`NULL`), defined time period (for example last 3 years).
- Output:
    - named list of values for quality criteria.
    - plots

## Function `quality.measures()`

- 1  How different the various approaches really are?
    - MAPE, MaxAPE
- 2 Inconsistencies
    - Incons
- 3 Quality of the seasonal adjustment
    - MQstat
- 4 Roughness of the components
    - R1, R2, R3, MarS, Mar1, Mar2


## Function `quality.measures()`

- 5 Idempotency
    - SA_test
- 6 Stability of the seasonally adjusted series
    - *not implemented*
- 7 Impact on the business cycle estimation
    - *not implemented*
- 8 Characteristics of the irregular component
    - Ireg_Stat





## Step 2

Functions for running tests on spreadsheets of time series (`tssda` and `tssia`).
- Input: two tables with time series.
- Output:
    - table (or list) with quality criteria.
    - plots


## Step 3

Functions for doing seasonal adjuestment (with [RJDemetra](https://jdemetra.github.io/rjdemetra/)) and aggregation of time series (with [KIX](https://immurb.github.io/pages/kix/)) and computing quality criteria for all time series.

- Input: time series, weights and aggregation specification (how to define in R? formulas?).
- Output:
    - table (or list) with quality criteria.
    - plots


## Availability and future development

- [https://github.com/CSBLatvia/SA-indirect-quality](https://github.com/CSBLatvia/SA-indirect-quality)
- Possible cooperation with the [persephone](https://statistikat.github.io/persephone/):
    - R package - an object oriented wrapper around the R Package RJDemetra, which performs time series adjustments with the java library JDemetra+
